package demorestapi.demo_restapi.controller.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import demorestapi.demo_restapi.controller.UserOperation;
import demorestapi.demo_restapi.entity.UserEntity;
import demorestapi.demo_restapi.service.UserService;

//controller object -> service object.method()
//controller oject -....
@RestController //controller call service, service call DB
@RequestMapping
public class UserController implements UserOperation {

  @Autowired
  private UserService userService;

  @Override
   public UserEntity createUser(UserEntity createUser){
    return userService.save(createUser);
  }
  
}
//repository class is generated by hinernate